# Generated by Django 5.2.5 on 2025-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_count',
            field=models.IntegerField(db_default=50000),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
