# Generated by Django 5.2.5 on 2025-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_genre_type_rename_date_project_insertion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='projects.type'),
        ),
    ]
