# Generated by Django 5.2.5 on 2025-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='target_count',
            new_name='word_count',
        ),
        migrations.AlterField(
            model_name='project',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=models.SET(1), to='projects.type'),
        ),
    ]
