# Generated by Django 5.2.5 on 2025-10-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_target_count_progress_word_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=models.SET(1), to='projects.type', verbose_name='Type'),
        ),
    ]
